apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
type: Opaque
data:
    # --- Grafana Admin ---
    GF_SECURITY_ADMIN_USER: YWRtaW4=    # admin
    GF_SECURITY_ADMIN_PASSWORD: YWRtaW4=    # admin

    # --- PgAdmin Admin ---
    PGADMIN_DEFAULT_EMAIL: YWRtaW5AcGxhdGZvcm1vbmUuY29t #admin@platformone.com
    PGADMIN_DEFAULT_PASSWORD: YWRtaW4= # admin

    # --- Spring Boot App Secrets ---
    JWT_SECRET: bXlTZWNyZXRLZXk5dDgzNGh0ZzkyaGZvODI0aHQ4MjRoZnU0aGZpMjRnZnl1MmVmODc0Z3RmdXliZnU=    # mySecretKey9t834htg92hfo824ht824hfu4hfi24gfyu2ef874gtfuybfu
    INTERNAL_API_KEY: MThFQ0U2QTRFRUE5QzJGRUE1MzczQTE0ODdCNDE=  # 18ECE6A4EEA9C2FEA5373A1487B41